labels:
  - name: Backlog
    description: Added to team backlog.
    color: 1d76db
  - name: Bug
    description: Something isn't working.
    color: d73a4a
  - name: Dependencies
    description: Changes to dependencies.
    color: 0366d6
  - name: Developer Experience
    description: Improvements or additions related to developer experience.
    color: a4418d
  - name: Documentation
    description: Improvements or additions to documentation.
    color: 0075ca
  - name: Duplicate
    description: This issue or pull request already exists.
    color: cfd3d7
  - name: Enhancement
    description: New feature or improvement.
    color: a2eeef
  - name: Feature Request
    description: Request for a new feature.
    color: c2e0c6
  - name: Help Wanted
    description: Extra attention is needed.
    color: 008672
  - name: Invalid
    description: This doesn't seem right.
    color: e4e669
  - name: Question
    description: Further information is requested.
    color: d876e3
  - name: Security
    description: Improvements or additions related to security.
    color: 15631c
  - name: Skip Changelog Update
    description: Changing changelog is not required.
    color: 7fac53
  - name: Test
    description: Improvements or additions related to testing.
    color: 7fac53
  - name: Triage
    description: The issue must be triaged.
    color: 7fac53
  - name: Wont Fix
    description: This will not be worked on.
    color: ffffff

repos:
  - name: gmarciani/markov-solver
    labels:
      - Backlog
      - Bug
      - Dependencies
      - Developer Experience
      - Documentation
      - Duplicate
      - Enhancement
      - Feature Request
      - Help Wanted
      - Invalid
      - Question
      - Security
      - Skip Changelog Update
      - Test
      - Triage
      - Wont Fix