blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/gmarciani/markov-solver/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/gmarciani/markov-solver/security/advisories/new
    about: Please report security vulnerabilities here.
